import type { Child, FC } from 'hono/jsx';
import { REPO_URL } from '@/lib/site';
// Tailwind-built stylesheet, imported as raw text via the wrangler Text rule
// (see wrangler.jsonc) and inlined below. Generated by `pnpm build:css`.
// eslint-disable-next-line import/default
import CSS from '../styles/app.css';

function Mark(props: { class?: string }): ReturnType<FC<{ class?: string }>> {
    return (
        <svg
            class={props.class ?? 'h-7 w-7'}
            viewBox="0 0 100 100"
            fill="none"
            aria-hidden="true"
        >
            <g fill="currentColor">
                <rect
                    x="22"
                    y="68"
                    width="36"
                    height="12"
                    rx="6"
                    opacity="0.4"
                />
                <rect
                    x="32"
                    y="48"
                    width="36"
                    height="12"
                    rx="6"
                    opacity="0.7"
                />
                <rect
                    x="42"
                    y="28"
                    width="36"
                    height="12"
                    rx="6"
                />
            </g>
        </svg>
    );
}

function Wordmark(props: {
    class?: string;
}): ReturnType<FC<{ class?: string }>> {
    return (
        <span
            class={`wm font-display font-medium tracking-[-0.05em] ${props.class ?? ''}`}
        >
            token<span class="max">maxer</span>
            <span class="tld">.quest</span>
        </span>
    );
}

/** GitHub mark (octicon, 16px grid). Decorative — the link carries the label. */
function GitHubMark(): ReturnType<FC> {
    return (
        <svg
            class="site-github__mark"
            viewBox="0 0 16 16"
            width="18"
            height="18"
            fill="currentColor"
            aria-hidden="true"
        >
            <path d="M8 0c4.42 0 8 3.58 8 8a8.013 8.013 0 0 1-5.45 7.59c-.4.08-.55-.17-.55-.38 0-.27.01-1.13.01-2.2 0-.75-.25-1.23-.54-1.48 1.78-.2 3.65-.88 3.65-3.95 0-.88-.31-1.59-.82-2.15.08-.2.36-1.02-.08-2.12 0 0-.67-.22-2.2.82-.64-.18-1.32-.27-2-.27-.68 0-1.36.09-2 .27-1.53-1.03-2.2-.82-2.2-.82-.44 1.1-.16 1.92-.08 2.12-.51.56-.82 1.28-.82 2.15 0 3.06 1.86 3.75 3.64 3.95-.23.2-.44.55-.51 1.07-.46.21-1.61.55-2.33-.66-.15-.24-.6-.83-1.23-.82-.67.01-.27.38.01.53.34.19.73.9.82 1.13.16.45.68 1.31 2.69.94 0 .67.01 1.3.01 1.49 0 .21-.15.45-.55.38A7.995 7.995 0 0 1 0 8c0-4.42 3.58-8 8-8Z" />
        </svg>
    );
}

/** Hamburger / close glyph for the mobile nav disclosure. */
function MenuMark(): ReturnType<FC> {
    return (
        <svg
            class="site-nav-menu__mark"
            viewBox="0 0 16 16"
            width="18"
            height="18"
            fill="none"
            stroke="currentColor"
            stroke-width="1.5"
            stroke-linecap="round"
            aria-hidden="true"
        >
            <path
                class="site-nav-menu__bar site-nav-menu__bar--a"
                d="M2.5 4.5h11"
            />
            <path
                class="site-nav-menu__bar site-nav-menu__bar--b"
                d="M2.5 8h11"
            />
            <path
                class="site-nav-menu__bar site-nav-menu__bar--c"
                d="M2.5 11.5h11"
            />
        </svg>
    );
}

const NAV_LINKS = [
    { href: '/', label: 'Leaderboard' },
    { href: '/hackathons', label: 'Hackathons' },
    { href: '/start', label: 'Get started' },
    { href: '/about', label: 'About' },
] as const;

/** Close mobile nav when clicking outside the disclosure. */
const NAV_SCRIPT = `(() => {
  const menu = document.querySelector('details.site-nav-menu');
  if (!menu) return;
  document.addEventListener('click', (e) => {
    if (!menu.open) return;
    if (!menu.contains(e.target)) menu.open = false;
  });
})();`;

const SITE_DESCRIPTION =
    'tokenmaxer.quest — a public leaderboard of tokens burned by AI builders on Claude Code, Codex, opencode and pi.';

const DEFAULT_OG_IMAGE_ALT =
    'tokenmaxer.quest — token leaderboard for AI builders';

type LayoutProps = {
    title: string;
    base: string;
    children?: Child;
    description?: string;
    ogImage?: string;
    ogUrl?: string;
    ogImageAlt?: string;
    /** Homepage: hide header until scroll, then fade/slide in. */
    revealChrome?: boolean;
};

export const Layout: FC<LayoutProps> = (props) => {
    const origin = props.base.replace(/\/$/u, '');
    const description = props.description ?? SITE_DESCRIPTION;
    const ogImage = props.ogImage ?? `${origin}/og.png`;
    const ogUrl = props.ogUrl ?? origin;
    const ogImageAlt = props.ogImageAlt ?? DEFAULT_OG_IMAGE_ALT;
    const chromeClass = props.revealChrome
        ? 'site-chrome site-chrome--reveal z-50 flex items-center justify-between gap-x-6 border-b border-border bg-canvas/60 px-5 py-3.5 backdrop-blur-xl backdrop-saturate-150 sm:px-8'
        : 'site-chrome sticky top-0 z-50 mb-2 flex items-center justify-between gap-x-6 border-b border-border bg-canvas/95 px-5 py-3.5 backdrop-blur-sm sm:px-8';
    return (
        <html lang="en">
            <head>
                <meta charset="utf-8" />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <title>{props.title}</title>
                <meta
                    name="description"
                    content={description}
                />
                <meta
                    name="theme-color"
                    content="#0a0a0a"
                />
                <link
                    rel="icon"
                    href="/favicon.svg"
                    type="image/svg+xml"
                />
                <link
                    rel="icon"
                    href="/favicon-32x32.png"
                    type="image/png"
                    sizes="32x32"
                />
                <link
                    rel="icon"
                    href="/favicon-16x16.png"
                    type="image/png"
                    sizes="16x16"
                />
                <link
                    rel="apple-touch-icon"
                    href="/apple-touch-icon.png"
                    sizes="180x180"
                />
                <link
                    rel="manifest"
                    href="/site.webmanifest"
                />
                <meta
                    property="og:type"
                    content="website"
                />
                <meta
                    property="og:site_name"
                    content="tokenmaxer.quest"
                />
                <meta
                    property="og:title"
                    content={props.title}
                />
                <meta
                    property="og:description"
                    content={description}
                />
                <meta
                    property="og:url"
                    content={ogUrl}
                />
                <meta
                    property="og:image"
                    content={ogImage}
                />
                <meta
                    property="og:image:width"
                    content="1200"
                />
                <meta
                    property="og:image:height"
                    content="630"
                />
                <meta
                    property="og:image:alt"
                    content={ogImageAlt}
                />
                <meta
                    name="twitter:card"
                    content="summary_large_image"
                />
                <meta
                    name="twitter:title"
                    content={props.title}
                />
                <meta
                    name="twitter:description"
                    content={description}
                />
                <meta
                    name="twitter:image"
                    content={ogImage}
                />
                <link
                    rel="preconnect"
                    href="https://fonts.googleapis.com"
                />
                <link
                    rel="preconnect"
                    href="https://fonts.gstatic.com"
                    crossorigin="anonymous"
                />
                <link
                    href="https://fonts.googleapis.com/css2?family=Mona+Sans:wght@500;600;700;800;900&family=Inter:opsz,wght@14..32,400;14..32,500&display=swap"
                    rel="stylesheet"
                />
                {/* eslint-disable-next-line */}
                <style dangerouslySetInnerHTML={{ __html: CSS }} />
                {props.revealChrome ? (
                    <noscript>
                        {/* Scrub is JS-driven; without it the bar is simply always there. */}
                        {/* eslint-disable-next-line */}
                        <style
                            dangerouslySetInnerHTML={{
                                __html: '.site-chrome--reveal{--chrome-p:1;position:sticky;pointer-events:auto}',
                            }}
                        />
                    </noscript>
                ) : null}
            </head>
            <body>
                <a
                    class="skip-link"
                    href="#main"
                >
                    Skip to content
                </a>
                <header
                    id="site-chrome"
                    class={chromeClass}
                >
                    <a
                        class="nav-link flex min-w-0 items-center gap-2.5 text-text no-underline hover:no-underline"
                        href="/"
                    >
                        <Mark />
                        <Wordmark class="truncate text-sm tracking-[-0.02em] sm:text-[15px]" />
                    </a>
                    <nav
                        class="site-nav"
                        aria-label="Primary"
                    >
                        <div class="site-nav__desktop">
                            {NAV_LINKS.map((link) => (
                                <a
                                    key={link.href}
                                    class="nav-link text-muted no-underline hover:text-text hover:no-underline"
                                    href={link.href}
                                >
                                    {link.label}
                                </a>
                            ))}
                            <span class="flex items-center gap-3">
                                <span
                                    class="h-4 w-px bg-border"
                                    aria-hidden="true"
                                />
                                <a
                                    class="nav-link -mr-1.5 inline-flex h-9 w-9 items-center justify-center rounded-md text-muted no-underline transition-colors duration-150 hover:bg-panel hover:text-text hover:no-underline"
                                    href={REPO_URL}
                                    target="_blank"
                                    rel="noopener noreferrer"
                                    aria-label="tokenmaxer on GitHub"
                                >
                                    <GitHubMark />
                                </a>
                            </span>
                        </div>
                        <details class="site-nav-menu">
                            <summary
                                class="site-nav-menu__trigger"
                                aria-label="Open menu"
                            >
                                <MenuMark />
                            </summary>
                            <div class="site-nav-menu__panel">
                                {NAV_LINKS.map((link) => (
                                    <a
                                        key={link.href}
                                        class="site-nav-menu__link nav-link"
                                        href={link.href}
                                    >
                                        {link.label}
                                    </a>
                                ))}
                                <a
                                    class="site-nav-menu__link nav-link site-nav-menu__link--github"
                                    href={REPO_URL}
                                    target="_blank"
                                    rel="noopener noreferrer"
                                    aria-label="tokenmaxer on GitHub"
                                >
                                    <GitHubMark />
                                    <span>GitHub</span>
                                </a>
                            </div>
                        </details>
                    </nav>
                </header>
                {/* eslint-disable-next-line */}
                <script dangerouslySetInnerHTML={{ __html: NAV_SCRIPT }} />
                <div class="mx-auto max-w-[1199px] px-5 pb-20 sm:px-8">
                    <main id="main">{props.children}</main>

                    <footer class="mt-24 grid gap-10 border-t border-border pt-12 text-[13px] text-muted md:grid-cols-[1.4fr_1fr_1fr]">
                        <div>
                            <a
                                class="nav-link mb-4 flex items-center gap-2.5 text-text no-underline hover:no-underline"
                                href="/"
                            >
                                <Mark class="h-6 w-6" />
                                <Wordmark class="text-sm" />
                            </a>
                            <p class="max-w-[36ch] leading-snug">
                                Self-reported, honor-system token counts from
                                Claude Code, Codex, opencode &amp; pi. No
                                prompts, no PII.
                            </p>
                        </div>
                        <div class="flex flex-col gap-2.5">
                            <span class="mb-1 font-display text-[13px] font-semibold tracking-[-0.13px] text-text">
                                Product
                            </span>
                            <a
                                class="nav-link text-muted no-underline hover:text-text"
                                href="/"
                            >
                                Leaderboard
                            </a>
                            <a
                                class="nav-link text-muted no-underline hover:text-text"
                                href="/hackathons"
                            >
                                Hackathons
                            </a>
                            <a
                                class="nav-link text-muted no-underline hover:text-text"
                                href="/start"
                            >
                                Get started
                            </a>
                            <a
                                class="nav-link text-muted no-underline hover:text-text"
                                href="/about"
                            >
                                About
                            </a>
                            <a
                                class="nav-link text-muted no-underline hover:text-text"
                                href="/pricing"
                            >
                                Pricing
                            </a>
                            <a
                                class="nav-link text-muted no-underline hover:text-text"
                                href="/footprint"
                            >
                                Footprint
                            </a>
                        </div>
                        <div class="flex flex-col gap-2.5">
                            <span class="mb-1 font-display text-[13px] font-semibold tracking-[-0.13px] text-text">
                                How it works
                            </span>
                            <a
                                class="nav-link text-muted no-underline hover:text-text"
                                href="/privacy"
                            >
                                Privacy &amp; honor system
                            </a>
                            <a
                                class="nav-link text-muted no-underline hover:text-text"
                                href="/start"
                            >
                                Install hooks
                            </a>
                        </div>
                    </footer>
                </div>
            </body>
        </html>
    );
};
